# Generated by Django 6.0.5 on 2026-05-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
