# Generated by Django 6.0.5 on 2026-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_remove_document_status_document_extracted_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('not_supported', 'Not_Supported')], default='uploaded', max_length=20),
        ),
    ]
