# Generated by Django 6.0.5 on 2026-06-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embeddings',
            field=models.BooleanField(default=False),
        ),
    ]
