# Generated by Django 6.0.5 on 2026-08-03 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatsession',
            name='unique_user_document_session',
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.document'),
        ),
    ]
