# Generated by Django 6.0.5 on 2026-08-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0013_remove_chatsession_unique_user_document_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
