# Generated by Django 6.0.5 on 2026-08-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page', models.CharField(choices=[('chat', 'Chat'), ('documents', 'Documents'), ('notes', 'Notes'), ('history', 'History')], default='chat', max_length=20)),
                ('confirm_before_delete', models.BooleanField(default=True)),
                ('animations', models.BooleanField(default=True)),
                ('conversation_memory', models.BooleanField(default=True)),
                ('auto_generate_chat_titles', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
