# Generated by Django 6.0.5 on 2026-08-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=120)),
                ('open_to_work', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='developer/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='developer/')),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('leetcode', models.URLField(blank=True)),
                ('hackerrank', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Portfolio',
                'verbose_name_plural': 'Developer Portfolio',
            },
        ),
    ]
