# Generated by Django 6.0.5 on 2026-08-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_developerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeveloperProfile',
        ),
    ]
